### ISSUE TITLE
Feature request : pthread support

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/ckb-vm#102]
Is ckb-vm support Linux-ELF/glibc toolchain ? I need some function like `pthread` in my ckb script, but only  Linux-ELF/glibc support pthread library.

**Comment by doitian** [comment]
Could you provide more insights why glibc and pthread library are important to write code for on chain verifiers in CKB?

We believe that glibc and pthread are too heavy. Especially pthread, CKB will not expose any operating system resources such as threads, locks to the VM.

**Comment by xxuejie** [comment]
Due to the design of CKB VM, threading will probably never be a supproted feature, there might be a way to support glibc but so far we failed to see a proper use case. It might be better if you can expand on your requirement here, a different approach might exist.
