### ISSUE TITLE
rdtsc function support

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/ckb-vm#105]
Is ckb-vm support `rdtsc()`  function ? Or is there anyway to get computational cycles in ckb script ?

**Comment by xxuejie** [comment]
`rdtsc` is not feasible, tho we can add current consumed cycle as a syscall. There is talk about it in the design phase but due to some reasons it didn't make into the mainnet version. We can probably add it in the next upgrade.

**Comment by mohanson** [comment]
`current_cycles` has been added at ckb2021.

https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0034-vm-syscalls-2/0034-vm-syscalls-2.md
