### ISSUE TITLE
Disable args initialize in CKB

### ISSUE THREAD

**Issue by jjyr** [nervosnetwork/ckb-vm#106]
Due to CKB's design, programs receive no args in the verification phase. But CKB-VM always does the `initialize_stack`, as a result, CKB-VM always puts a `0` (length of args) on the top of the stack, which makes no-sense.

https://github.com/nervosnetwork/ckb-vm/blob/develop/src/machine/mod.rs#L138

It's a bit strange, and if users try to customize memory layout through the linker script, the default behavior may override some data undesirable.

We can add a new flag to the VM and automatically disable args initialization on the future version of CKB-VM. (need to be applied on the next hard-fork)

**Comment by mohanson** [comment]
After testing, I am sure that it is necessary to initialize the stack. If we do not initialize, it means that the SP is located at the highest address of the memory, and then the `_start` section will cause an error when it is executed here:

```
00000000000100c8 <_start>:
   100c8:       00002197                auipc   gp,0x2
   100cc:       bf018193                addi    gp,gp,-1040 # 11cb8 <__global_pointer$>
   100d0:       f6018513                addi    a0,gp,-160 # 11c18 <_edata>
   100d4:       f9818613                addi    a2,gp,-104 # 11c50 <__BSS_END__>
   100d8:       8e09                    sub     a2,a2,a0
   100da:       4581                    li      a1,0
   100dc:       16e000ef                jal     ra,1024a <memset>
   100e0:       00000517                auipc   a0,0x0
   100e4:       30650513                addi    a0,a0,774 # 103e6 <atexit>
   100e8:       c519                    beqz    a0,100f6 <_start+0x2e>
   100ea:       00000517                auipc   a0,0x0
   100ee:       2c850513                addi    a0,a0,712 # 103b2 <__libc_fini_array>
   100f2:       2f4000ef                jal     ra,103e6 <atexit>
   100f6:       0ea000ef                jal     ra,101e0 <__libc_init_array>
***100fa:       4502                    lw      a0,0(sp) ************************** Cause an OutOfBounds error
   100fc:       002c                    addi    a1,sp,8
   100fe:       4601                    li      a2,0
   10100:       0b2000ef                jal     ra,101b2 <main>
   10104:       0be0006f                j       101c2 <exit>
```

**Comment by mohanson** [comment]
I see one way this could be addressed, SP still moves, but does not write data(argc) to the top of the stack.
