### ISSUE TITLE
Suspend/resume a running VM

### ISSUE THREAD

**Issue by xxuejie** [nervosnetwork/ckb-vm#109]
We should be able to suspend a running CKB VM, save the states somewhere, and resume the previously running VM at a latter time, or even on a different machine. One potential design here might be:

* A signal is sent from another thread to CKB VM to start suspending
* CKB VM will pack the current register states, as well as any dirty memory pages in a packed data structure. Notice we can easily exclude the following memory pages from dirty memory page list:
    + Page with all zeros as the data
    + All executable pages, since they must come from some binaries
    + Writable pages coming from an ELF, but hasn't been modified in any way.
* Then the packed data structure can be restored elsewhere into a running VM instance that is exactly the same as what it is before suspending. Execution can then continue from there.

**Comment by mohanson** [comment]
In the above design, the ELF binary needs to be reloaded again when the VM is resumed. Have you considered just dumping the entire memory? there may be better performance.

**Comment by xxuejie** [comment]
I was under the impression that the ELF binary will be available elsewhere(for example: in CKB this will be in a cell). Dumping the entire memory might result in much bigger memory consumption. Consider the fact that it is typically long running programs that would require suspend/resume, I would bet that loading the binary again is a acceptable tradeoff to reduce load on memory & (possibly) disk requirements.

**Comment by xxuejie** [comment]
One additional idea from @doitian: instead of using a signal, we can simply allow suspending when the available cycles are all consumed. That will suit CKB's use case much better.
