### ISSUE TITLE
Cycle profile support

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/ckb-vm#110]
When deal with high cycle cost contract, if we send such a transaction may been rejected due to the [vm cycle limit](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0014-vm-cycle-limits/0014-vm-cycle-limits.md) (which is `max_block_cycles`).

A cycle profile tool would be helpful to optimize the contract code.

**Comment by xxuejie** [comment]
https://docs.nervos.org/docs/essays/pprof
