### ISSUE TITLE
Replace `memmap` crate since it is unmaintained

### ISSUE THREAD

**Issue by chaoticlonghair** [nervosnetwork/ckb-vm#119]
https://github.com/nervosnetwork/ckb-vm/blob/99276b230859248e412ec72b585176884bc5d3f2/Cargo.toml#L28

The crates [`mapr`] or [`memmap2`] may be reasonable alternatives.

### References
- [Is this crate still maintained?](https://github.com/danburkert/memmap-rs/issues/90)
- [memmap looks abandonned](https://github.com/RustSec/advisory-db/issues/359)
- [RUSTSEC-2020-0077: memmap: memmap is unmaintained](https://rustsec.org/advisories/RUSTSEC-2020-0077)

[`mapr`]: https://crates.io/crates/mapr
[`memmap2`]: https://crates.io/crates/memmap2

**Comment by mohanson** [comment]
mapr and memmap2 seem to only fork the upstream code, so either one is ok. I will submit a pr later.
