### ISSUE TITLE
Upgrade goblin to 0.3.5

### ISSUE THREAD

**Issue by brson** [nervosnetwork/ckb-vm#143]
**Describe the bug**

Goblin <= 0.3.4 contains an arithmetic overflow decoding bad elf metadata.

It is fixed by https://github.com/m4b/goblin/pull/260 but not yet released.

The overflow in question is here https://github.com/m4b/goblin/blob/0dbaa385dbba8f56267febe0ff8fd7eda23acc39/src/elf/mod.rs#L409

In debug mode the loader will panic. In release mode, further sanity checks in the loader should prevent anything catastrophic, but I have only read the code briefly.

**To Reproduce**

I can provide an elf binary that reproduces the error on request.

cc @mohanson @xxuejie

**Comment by mohanson** [comment]
I think we can add a test case first and mark the test case as `#[ignore]` until goblin releases a new version

**Comment by brson** [comment]
I'll add that case.
