### ISSUE TITLE
Use `reset()` as a general means to reuse machine

### ISSUE THREAD

**Issue by mohanson** [nervosnetwork/ckb-vm#161]
In the current CKB, a new machine needs to be created every time a script is executed, which means a malloc with a size of at least 4M. I consider using `reset()` to reset the state of the machine after each script execution is over, as shown below

```rs
// Start execute first script
machine.run()

// Reset states of machine
machine.reset()
machine.set_max_cycles(_)
machine.set_cycles(0)

// Start execute next script
machine.load_program(_)
machin.run()
```

But now there is a problem to think about: this approach breaks isolation. 

cc @driftluo

**Comment by xxuejie** [comment]
I think this approach works: the design of reset is ensures that after resetting the machine, all data from previous machine has been *erased*, can you elaborate on why this new approach breaks isolation?

**Comment by xxuejie** [comment]
In addition, I wasn't sure on this snippet:

```
machine.reset()
machine.set_max_cycles(_)
machine.set_cycles(0)
```

`reset` is designed to, well, reset everything, so why bother setting cycles to 0 here?

**Comment by driftluo** [comment]
>  why bother setting cycles to 0 here?

When CKB Fork, the temporarily stored VM can have 2 versions. The control of cycles cannot be controlled by the VM. It is necessary to reset the `max_cycles` at the CKB level at each reset.

**Comment by mohanson** [comment]
1) `.cycles()` record all the cycles used by the machine from birth to death, not just a specific script. Therefore `reset()` does not reset cycles, and its behavior conforms to `exec()`.

2) From a low-level perspective, the data recorded in the memory by the previous script has not been erased.

**Comment by xxuejie** [comment]
I see the point of resetting cycles in the term of suspend/resume. But I wasn't sure why the versions of VM affects cycles. Current `reset` function, as far as I know, won't clear syscalls, won't swap to different version. So if we are using different versions of VM, we will have to initialize different VM instances, we cannot use `reset` there.

**Comment by xxuejie** [comment]
> From a low-level perspective, the data recorded in the memory by the previous script has not been erased.

But the VM, after resetting, can never read the data written by previous scripts. Lazy initialization will take place here: once you try to access a page, it will be initialized, and zeroed first. So unless there is a bug, I don't think we have any isolation problem.

**Comment by driftluo** [comment]
> I see the point of resetting cycles in the term of suspend/resume. But I wasn't sure why the versions of VM affects cycles. Current `reset` function, as far as I know, won't clear syscalls, won't swap to different version. So if we are using different versions of VM, we will have to initialize different VM instances, we cannot use `reset` there.


```
pub struct TransactionScriptsVerifier<'a, DL> {
    ...
    current_cycles: Cycle,
    #[cfg(has_asm)]
    machine_v1: Option<AsmMachine<'a>>,
    #[cfg(has_asm)]
    machine_v2: Option<AsmMachine<'a>>,
}
```
A transaction may require two versions of VMs to execute. First, we initialize max_cycles to two VMs. However, they are not shared. The execution group may be in any VM. If max_cycles cannot be changed dynamically, there may be a problem that the upper limit cannot be controlled. It may run beyond our expected cycle size

Each time a script is executed, reset the current cycles to zero and modify the `max_cycles` of both VMs to the current remaining size to use the `reset` function to reuse VMs

**Comment by xxuejie** [comment]
> If max_cycles cannot be changed dynamically

I'm not talking about setting max cycles, I'm just merely saying setting current cycles to zero after reset operation, is useless, since reset operation should already set current cycles to zero.

**Comment by driftluo** [comment]
> since reset operation should already set current cycles to zero.

This is wrong. If reset will cause the current recorded cycle to be zero, there will be a problem with the exec billing

**Comment by xxuejie** [comment]
> This is wrong. If reset will cause the current recorded cycle to be zero, there will be a problem with the exec billing

Here we are mixing 2 independent things:

* The semantic of `reset` in ckb-vm, would be like hitting the reset button on a computer, where it boots from the original state again. In this case, cycles should naturally be set to zero, arguably, it might make sense to reset max cycles to zero as well.
* Then there is the issue of implementing exec as a syscalls, if exec requires preserving cycles, we should do that in the exec syscall as well. It does not make sense saying cycles should be preserve, since there will be a problem when we implement exec.

**Comment by mohanson** [comment]
After discussion, two changes are expected:

1) cycles should be set to 0 in `reset()`

2) The signature of `reset()` becomes `reset(max_cycles: u64)` to allow max_cylces to be set
