### ISSUE TITLE
Remove confusing constructor like `machine::latest()` or `machine::default()`

### ISSUE THREAD

**Issue by mohanson** [nervosnetwork/ckb-vm#163]
Since we have two different versions now, and the supported instruction sets include IMC, B, MOP, `latest()` and `default()` bring more confusion than their benefits, so I recommend removing them.

Related code:

- https://github.com/nervosnetwork/ckb-vm/blob/develop/src/machine/mod.rs#L365-L371
- https://github.com/nervosnetwork/ckb-vm/blob/develop/tests/test_asm.rs#L26

**Comment by xxuejie** [comment]
I think we can pull the trigger here. I don't have any arguments for having them in the API now

**Comment by mohanson** [comment]
Merged.
