### ISSUE TITLE
Missing syscalls required for dynamic allocation

### ISSUE THREAD

**Issue by TheRealBluesun** [nervosnetwork/ckb-vm#26]
Syscalls for malloc() and free() are missing (e.g. 214 `brk()`).  I've considered starting to implement them, but don't know how much is due to change in the near future.

Very cool project!

(还有我会说一点儿普通话可是我说的不好，我不知道这里有没有会说中文的人）

**Comment by xxuejie** [comment]
Hi,

Actually, you don't need `brk` to implement malloc, we do have an example contract running `mruby`, which involves a lot of malloc, https://github.com/nervosnetwork/mruby-contracts and runs perfectly fine. The trick to this is to use a modified version of libc which works in userspace without needing `brk`: https://github.com/nervosnetwork/riscv-newlib/commit/dbc4aa7eb117ab9ccab2aeedcf016508a930ff23

To answer your question more directly: we thought a lot about whether we want `brk`, in fact, at some earlier [stage](https://github.com/nervosnetwork/ckb-vm/commit/fa394b675b0cdf85ce2a75e03334045b70fcf01b) of this project, we do implement a MMU which can enable `brk`, but later we decided to [remove](https://github.com/nervosnetwork/ckb-vm/commit/023f0731d1e48a45a30e9f38b8e10059df6816cf) it completely. The reason behind this, is that we believe CKB VM should be as simple as possible, while an MMU might help developing a contract, in production you really want the maximum performance, and the minimal attack surface. Plus, any MMU we implement here will only be nice to one kind of application, but might bring obstacles to applications with different memory usage patterns.

As a result, we decide to go without MMU nor `brk` in the official CKB spec, and defer to modifications in libc to implement malloc and free.

BTW: we do speak both English and Chinese but let's keep using English here for broader audience :)

**Comment by TheRealBluesun** [comment]
Thank you so much for getting back to me so quickly.  Reading through, I better understand that decision -- that makes sense.  I'll play around with that `newlib` implementation you shared.  Thank you!

（好的 😊 在这里我会只用英语）
