### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by koute** [nervosnetwork/ckb-vm#388]
I'm currently writing a new RISC-V based virtual machine and I'm slowly building up a benchmark suite of programs to cross-compare my VM to other VMs available in the ecosystem. I recently added CKBVM, and here are the results for one of my benchmarks:

   * Native: 3.774ms
   * PolkaVM: 6.033ms
   * Wasmtime: 6.054ms
   * Wasmer (singlepass): 14.307ms
   * Wazero: 21.621ms
   * Wasm3: 109ms
   * Wasmi (register): 114ms
   * Wasmi (stack): 212ms
   * **CKB VM: 1.020s**

This was very surprising to me, because this is slower than a pure Rust WASM interpreter (Wasmi), and it's even slower than a pure Rust RISC-V interpreter I wrote as a prototype a few months back in one day (I don't have concrete up to date numbers, but that one got around ~800ms on a very similar benchmark).

So I have two questions:
- Am I doing something horribly wrong which slows it down, or is this how it performs? [This](https://github.com/koute/polkavm/blob/master/tools/benchtool/src/backend/backend_ckbvm.rs) is how I call into CKB-VM, [this is the benchmark](https://github.com/koute/polkavm/blob/ea6e91a5857148d349d2b373e9caa25b04477def/guest-programs/bench-pinky/src/main.rs) (it's an NES emulator and the benchmark measures how long it takes for it to process a single frame) and [this is the entry point for CKB VM](https://github.com/koute/polkavm/blob/ea6e91a5857148d349d2b373e9caa25b04477def/guest-programs/bench-common.rs#L19)***.
- Are there plans to make it faster? Even with a totally naive recompiler I think you should be able to quite easily speed it up to at least ~50ms without much trouble.

The benchmark executable was, of course, compiled in release mode with full fat LTO and codegen units set to 1.

*** - Please note that there are two things I needed to do which CKB VM doesn't seem to support naturally, so I had to work around it:
- I need to call into the same program with the same memory multiple times without recompiling and reinitializing everything (I'm comparing execution performance here, not the compilation nor end-to-end total times!). I work around this by stashing the values of PC and the SP, and then restoring it every time I call back into the VM. This seems to work fine.
- I need to call two different exports from the guest program. CKB VM programs are supposed to be parametrized by setting up argv, but you can only do this once when loading the program, and I *don't* want to load the program multiple times - I want the benchmark to be fair and *not* measure the initialization! - so I completely ignore argv and just set the A0 register to tell the benchmark which entry point it's supposed to call.

Neither of these negatively affects the speed in any way, as far as I can see.

**Comment by XuJiandong** [comment]
Can you try `no_asm`  benchmarking? See https://github.com/nervosnetwork/ckb-vm/blob/11a59cf65eb3a04a4eae2cfb94f7e60bdfef154d/examples/ckb-vm-runner.rs#L66 for references.

If it is same as the old one, that might be something wrong (e.g. non x86-64 machine, wrong configurations)

**Comment by koute** [comment]
They're not the same, but they're not that far off:

```
Run #1:
runtime/pinky/ckbvm_asm: 1.063s
runtime/pinky/ckbvm_non_asm: 1.147s

Run #2:
runtime/pinky/ckbvm_asm: 1.069s
runtime/pinky/ckbvm_non_asm: 1.160s

Run #3:
runtime/pinky/ckbvm_asm: 1.073s
runtime/pinky/ckbvm_non_asm: 1.173s
```

So the ASM one is consistently faster, although only just by a little bit.

These are all run on a Threadripper 3970x on Linux.

If I'm doing something wrong I'd love to know what exactly. (:

**Comment by mohanson** [comment]
https://github.com/koute/polkavm/pull/69

I submitted a fix PR, which should result in a 10x+ improvement.

**Comment by koute** [comment]
Nice! Thanks! I knew I had to be doing something wrong! (:

New results:

```
runtime/pinky/ckbvm_asm: 140ms
runtime/pinky/ckbvm_non_asm: 1.128s
```

**Comment by koute** [comment]
Okay, so since the performance is not catastrophically bad anymore I'll go ahead and close this issue.

Thank you again for pointing out where I screwed up!

And I do hope you'll keep on improving the performance, as I will be rebenchmarking this regularly!
