### ISSUE TITLE
Unsoundness in cast_ptr_to_slice

### ISSUE THREAD

**Issue by lwz23** [nervosnetwork/ckb-vm#444]
**Describe the bug**
The `cast_ptr_to_slice` and `cast_ptr_to_slice_mut`function in the `AsmCoreMachine` struct is unsound. It uses the unsafe `std::slice::from_raw_parts` function without validating its inputs. This allows safe code to pass invalid parameters, such as null pointers or out-of-bounds sizes, which leads to undefined behavior (UB). This can cause crashes, segmentation faults, or other unpredictable behavior.

**To Reproduce**
1. Create an instance of `AsmCoreMachine`.
2. Call the `cast_ptr_to_slice` method with an invalid pointer (e.g., a null pointer or an arbitrary invalid memory address).
3. Attempt to access the returned slice.
4. Observe a runtime crash or memory access violation.

Example code to reproduce:
```
fn main() {
    let machine = AsmCoreMachine {
        registers: [0; RISCV_GENERAL_REGISTER_NUMBER],
        pc: 0,
        next_pc: 0,
        running: 0,
        cycles: 0,
        max_cycles: 0,
        chaos_mode: 0,
        chaos_seed: 0,
        load_reservation_address: 0,
        reset_signal: 0,
        isa: 0,
        version: 0,
        error_arg0: 0,
        memory_size: 0,
        frames_size: 0,
        flags_size: 0,
        last_read_frame: 0,
        last_write_page: 0,
        memory_ptr: 0,
        flags_ptr: 0,
        frames_ptr: 0,
    };

    // Invalid pointer (null pointer)
    let invalid_ptr: u64 = 0xdeadbeef; // Invalid memory address
    let offset = 0;
    let size = 10;

    let slice = machine.cast_ptr_to_slice(invalid_ptr, offset, size); // Triggers UB
    println!("{:?}", slice); // Causes crash or unpredictable behavior
}
```
**Expected behavior**
The function should validate the provided pointer, offset, and size to ensure they are safe and within bounds. If the inputs are invalid, it should return an error instead of allowing unsafe memory access.

**Environment**

OS: Windows 10
Version: Commit main branch or latest version
Rust: rustc 1.72.0

**Additional context**
 The crash manifests as a segmentation fault or access violation (STATUS_ACCESS_VIOLATION) when invalid parameters are passed to the cast_ptr_to_slice method. Below is the observed error message when running the example code:
`error: process didn't exit successfully: `target\debug\example.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

**Comment by mohanson** [comment]
Thank you for your report!

I understand your concerns regarding the `cast_ptr_to_slice` method using the unsafe `std::slice::from_raw_parts` function and its potential to cause undefined behavior. However, this is expected behavior and not a bug.

The `cast_ptr_to_slice` function is a low-level utility designed to work with raw pointers and create slices directly. By its nature, it relies on unsafe operations and assumes that the caller ensures the validity of the inputs. In Rust’s safety model, the use of unsafe signifies that the programmer, not the compiler, must uphold certain invariants. If invalid parameters (e.g., null pointers or out-of-bounds offsets) are provided, undefined behavior may occur, and this is an accepted trade-off in such scenarios.

For low-level, performance-sensitive functions like `cast_ptr_to_slice`, adding input validation would impose a runtime cost. To maximize performance, this function does not validate its parameters.

**Comment by lwz23** [comment]
Thank you for your detailed response! I appreciate your clarification regarding the design intent of the `cast_ptr_to_slice` function as a low-level utility and the trade-off between safety and performance. However, I believe there is an important consideration regarding Rust’s safety guarantees that may need to be addressed.

If the primary goal is to prioritize performance by avoiding runtime input validation, the function should ideally be marked as `unsafe`. This would explicitly communicate to users that they are responsible for ensuring the validity of the inputs and maintaining the required invariants. Additionally, the function should include comments or documentation outlining the preconditions necessary for safe usage.

Currently, as it stands, the function is callable from safe Rust code without requiring an `unsafe` block. This creates a situation where undefined behavior can occur if the user inadvertently passes invalid parameters, such as null pointers or out-of-bounds sizes. This design potentially violates Rust’s core safety model, which seeks to prevent memory unsafety in safe code. 

Marking the function as `unsafe` would not only align its design with Rust’s conventions but also provide clarity to developers regarding the risks and responsibilities associated with its usage. This adjustment would ensure that the expectations of Rust’s safety guarantees are upheld while still allowing the performance optimizations you mentioned.

Thank you again for your understanding and for considering this feedback!

**Comment by lwz23** [comment]
I think at least cast_ptr_to_slice should be marked as 'unsafe' if performance is considered as an important issue.

**Comment by lwz23** [comment]
Modification 1: Mark the function as unsafe
To align with Rust's safety model, the function can be marked as unsafe. This approach keeps the performance benefits and makes it explicit that the caller must ensure the safety of the inputs.
```
/// Casts a raw pointer with an offset and size to a byte slice.
///
/// # Safety
///
/// - The `ptr` must be a valid memory address for reading `size` bytes.
/// - The `ptr + offset` must not overflow.
/// - The memory region specified by `ptr + offset` and `size` must remain valid 
///   for the lifetime of the returned slice.
///
/// Failing to satisfy these conditions results in undefined behavior.
pub unsafe fn cast_ptr_to_slice(&self, ptr: u64, offset: usize, size: usize) -> &[u8] {
    let ptr = ptr as *const u8;
    let ptr = ptr.add(offset);
    std::slice::from_raw_parts(ptr, size)
}
```
Modification 2: Add input validation (safer but with a slight performance cost)
If input validation is acceptable, the function can return an Option<&[u8]> to handle invalid inputs gracefully. This ensures memory safety without requiring unsafe blocks.
```
pub fn cast_ptr_to_slice(&self, ptr: u64, offset: usize, size: usize) -> Option<&[u8]> {
    // Check if the pointer is non-zero
    if ptr == 0 {
        return None;
    }

    // Check if the offset causes an overflow
    let ptr = ptr as *const u8;
    if ptr as usize > usize::MAX - offset {
        return None;
    }

    // Check if adding offset results in a null or invalid pointer
    let ptr = unsafe { ptr.add(offset) };
    if ptr.is_null() {
        return None;
    }

    // Return a safe slice if all checks pass
    Some(unsafe { std::slice::from_raw_parts(ptr, size) })
}
```

**Comment by lwz23** [comment]
Here is the definition of soundness in Rust:
Soundness is a type system concept (actually originating from the study of logics) and means that the type system is "correct" in the sense that well-typed programs actually have the desired properties. For Rust, this means well-typed programs cannot cause Undefined Behavior. This promise only extends to safe code however; for unsafe code, it is up to the programmer to uphold this contract.

Accordingly, we say that a library (or an individual function) is sound if it is impossible for safe code to cause Undefined Behavior using its public API. **Conversely, the library/function is unsound if safe code can cause Undefined Behavior.**

**Comment by mohanson** [comment]
Thank you for your suggestions.

Modification 1 (Marking the function as unsafe): Approved. This aligns with Rust's safety model while maintaining performance. Making the function unsafe explicitly communicates the responsibility of ensuring input safety to the caller.

Modification 2 (Adding input validation): Not approved. While it improves safety, the slight performance cost introduced by runtime checks is not acceptable for this use case. The performance of this function is critical, and the responsibility for ensuring valid inputs will remain with the caller. Furthermore, your modification provides only a limited improvement in security. Can ptr be equal to 1 or 2?

Let me know if you have further questions or would like to discuss alternatives.

**Comment by lwz23** [comment]
I have no further questions. Thank you for taking my advice!

**Comment by lwz23** [comment]
Sorry for closing this issue in error, maybe it should be closed after the author changes it.
