### ISSUE TITLE
Get wrong exit code when exit code >= 128.

### ISSUE THREAD

**Issue by mohanson** [nervosnetwork/ckb-vm#86]
**Describe the bug**

```
$ cat main.c
```

```
int main() {
  return 128;
}
```

Run it by ckb-vm:

```
$  /usr/local/riscv/bin/riscv64-unknown-elf-gcc main.c -o main.riscv
```

```rs
use bytes::Bytes;
use std::io::Read;

fn main() {
    let args: Vec<Bytes> = std::env::args().map(|a| a.into()).collect();

    let mut file = std::fs::File::open("/tmp/main.riscv").unwrap();
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer).unwrap();
    let buffer = Bytes::from(buffer);

    let r = ckb_vm::run::<u64, ckb_vm::SparseMemory<u64>>(&buffer, &args[..]).unwrap();
    println!("{:?}", r);
}
```

output:

```
-128
```

**Comment by xxuejie** [comment]
Hi, right now this is expected behavior, CKB VM would shrink the exit code to 8-bit value similar to a UNIX platform. To aid debugging, we now use i8 here: https://github.com/nervosnetwork/ckb-vm/blob/develop/src/machine/mod.rs#L249, that's why 128 would be converted to -128, cuz i8 is not capable of holding a i8 value

**Comment by mohanson** [comment]
On POSIX systems the standard exit code is 0 for success and any number from 1 to 255 for anything else, I can't quite understand the benefits of using i8.

**Comment by xxuejie** [comment]
Like I mentioned above this is more a handy change for debugging. In c people use negative return value all the time, having i8 can be quite handy when debugging, besides i8 and u8 have the same value range.

That being said, I consider it a separate question if we should use i8 or u8, my point is the return value is not wrong, just different interpretation
