### ISSUE TITLE
Stack pointer not aligned

### ISSUE THREAD

**Issue by mohanson** [nervosnetwork/ckb-vm#97]
During stack initialization, as follows

https://github.com/nervosnetwork/ckb-vm/blob/develop/src/machine/mod.rs#L159

And as riscv-spec-v2.2.pdf, Page 77 says, "In the standard RISC-V calling convention, the stack pointer sp is always 16-byte aligned."

inconsistent behavior here.

**Comment by xxuejie** [comment]
Are you sure you are using the latest spec? I checked the latest version: https://github.com/riscv/riscv-isa-manual/releases/tag/draft-20200213-d1811f4 and I couldn't find the alignment rule as you mentioned

**Comment by mohanson** [comment]
Well, the version I see is indeed older, but I also found it at official website at:

https://riscv.org/specifications/isa-spec-pdf/, Page 125, foot of "C.ADDI16SP"

**Comment by xxuejie** [comment]
I see this now, yes this is an inconsistent behavior, like #98 I think we will have to make it an optional behavior for now and only enables them in the next fork

**Comment by xxuejie** [comment]
Fixed in #99
